=== antonioluqueparlon/EjerciciosClase/Parlon/LGMParlon/dtd/EjercicioVengadores.dtd
<!ELEMENT vengadores (superheroes,villanos,peliculas)*>
<!ENTITY % caracteristicasVengadores "universo CDATA #FIXED 'Marvel'">
<!ATTLIST universo %caracteristicasVengadores;>
<!ELEMENT superheroes (superheroe*)>
<!ELEMENT superheroe EMPTY>
<!ENTITY % caracteristicasPersonaje "nombre ID #REQUIRED
                                     poder CDATA #IMPLIED ">
<!ATTLIST superheroe %caracteristicasPersonaje;>                                     
<!ELEMENT villanos (villano*)>
<!ELEMENT villano EMPTY>
<!ENTITY % caracteristicasVillano "nombre ID #REQUIRED
                                    pelicula CDATA #IMPLIED">
<!ATTLIST villano %caracteristicasVillano;>
<!ELEMENT peliculas (pelicula*)>
<!ELEMENT pelicula EMPTY>
<!ELEMENT pelicula (nombrepelicula,fechaestreno)*>
<!ENTITY % caracteristicasPelicula "nombrepelicula ID #REQUIRED
                                    fechaestreno PCDATA #IMPLIED">

=== antonioluqueparlon/EjerciciosClase/Parlon/LGMParlon/dtd/EjercicioVengadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vengadores SYSTEM "EjercicioVengadores.dtd" >
<vengadores universo="Marvel">
<superheroes>
        <superheroe nombre="Thor" poder="Martillo"/>
        <superheroe nombre="IronMan" poder="Tecnologia"/>
        <superheroe nombre="SpiderMan" poder="TelaraÃ±a"/>


    </superheroes>

    <villanos>
        <villano nombre="Thanos" pelicula="EndGame"/>
        <villano nombre="Ultron" pelicula="AgeOfUltron"/> 
    </villanos>
    <peliculas>
        <pelicula nombrepelicula="EndGame" fechaestreno="2019"/>
        <pelicula nombrepelicula="Infinity War" fechaestreno="2018"/>
        <pelicula nombrepelicula="Edad De Ultron" fechaestreno="2015" />
        <pelicula nombrepelicula="AVengers" fechaestreno="2012"/>
    </peliculas>
</vengadores>
