=== antonioluqueparlon/EjerciciosClase/Parlon/LGMParlon/dtd/examen.dtd
<!NOTATION JPG SYSTEM "image/jpeg">

<!ELEMENT deportistas (famosos,hijos,tipoDeporte?)>
<!ENTITY % caracteristicasFamosos "tipo CDATA #FIXED 'Deportistas Famosos'">
<!ATTLIST deportistas %caracteristicasFamosos;>
<!ELEMENT famosos (deportista*)>
<!ELEMENT deportista EMPTY>
<!ENTITY % caracteristicasDeportistasFamosos "nombre ID #REQUIRED
                                    pelo CDATA #IMPLIED
                                    parentesco IDREFS #IMPLIED">
<!ATTLIST deportista %caracteristicasDeportistasFamosos;
                                    casadoCon IDREF #IMPLIED
                                    imagen NOTATION (JPG) #IMPLIED>
<!ELEMENT hijos (hijo+)>
<!ELEMENT hijo EMPTY>
<!ENTITY % caracteristicaHijos "nombre ID #REQUIRED
                            pelo CDATA #IMPLIED
                            parentesco IDREFS #IMPLIED">
<!ATTLIST hijo %caracteristicaHijos;>
<!ELEMENT tipoDeporte (#PCDATA | tipo)*>
<!ELEMENT tipo EMPTY>
<!ATTLIST tipo nombre (futbol|formula1|tenis|baloncesto|natacion) #REQUIRED
            categoria CDATA #REQUIRED
            relacionadoCon IDREFS #IMPLIED>

=== antonioluqueparlon/EjerciciosClase/Parlon/LGMParlon/dtd/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas SYSTEM "examen.dtd">
<deportistas tipo="Deportistas Famosos">
    <famosos>
        <deportista nombre="CarlosSainz" pelo="Moreno" casadoCon="CristianoRonaldo" parentesco="CarlosSainzJr"/>
        <deportista nombre="CristianoRonaldo" pelo="Moreno"/>
        <deportista nombre="FernandoAlonso" pelo="Pelirrojo"/>
        <deportista nombre="Messi" pelo="Rubio"/>
        <deportista nombre="UsainBolt" pelo="rapao"/>
        <deportista nombre="SergioRamos" pelo="castanio" />
        <deportista nombre="MichaelPhelps" />
    </famosos>
    <hijos>
        <hijo nombre="CristianoJr" pelo="Moreno" parentesco="CristianoRonaldo"/>
        <hijo nombre="CarlosSainzJr" pelo="Moreno" parentesco="CarlosSainz"/>
        <hijo nombre="MateoRamos" pelo= "rubio" parentesco="SergioRamos"/>
    </hijos>
    <tipoDeporte>
        <tipo nombre="futbol" categoria="pelota"/>
        <tipo nombre="formula1" categoria="motor" relacionadoCon="CarlosSainz FernandoAlonso"/>
        <tipo nombre="baloncesto" categoria="pelota"/>
        <tipo nombre="natacion" categoria="olimpico" relacionadoCon="MichaelPhelps"/>
    </tipoDeporte>
</deportistas>
